import src.questFolder.industry.assignFloorPlan
import src.questFolder.industry.brewPotion
import src.questFolder.industry.buildRoom
import src.questFolder.industry.convertToTraproom
import src.questFolder.industry.farmMold
import src.questFolder.industry.farmMoldTile
import src.questFolder.industry.freeUpStorage
import src.questFolder.industry.furnishRoom
import src.questFolder.industry.machinePlacing
import src.questFolder.industry.machining
import src.questFolder.industry.manufacture
import src.questFolder.industry.restockRoom
import src.questFolder.industry.configureManufacturingTable
import src.questFolder.industry.restockBase
