import src.itemFolder.artworks
import src.itemFolder.automation
import src.itemFolder.dungeon
import src.itemFolder.experimental
import src.itemFolder.foodProcessing
import src.itemFolder.functional
import src.itemFolder.furniture
import src.itemFolder.hacks
import src.itemFolder.health
import src.itemFolder.industry
import src.itemFolder.logistics
import src.itemFolder.manager
import src.itemFolder.military
import src.itemFolder.obsolete
import src.itemFolder.plants
import src.itemFolder.resources
import src.itemFolder.story
import src.itemFolder.workshops
import src.itemFolder.Potion