import urwid

wall = (urwid.AttrSpec("#d60",'default'),"⛝ ")
wall = (urwid.AttrSpec("#334",'default'),"⛝ ")
pipe = (urwid.AttrSpec("#337","default"),"✠✠")
corpse = "࿊ "
unconciousBody = "࿌ "
growthTank_filled= (urwid.AttrSpec("#3b3","default"),"⏣ ")
growthTank_unfilled = (urwid.AttrSpec("#3f3","default"),"⌬ ")
hutch_free = (urwid.AttrSpec("#3b3","default"),"Ѻ ")
hutch_occupied = (urwid.AttrSpec("#3f3","default"),"ꙭ ")
lever_notPulled = (urwid.AttrSpec("#bb3","default"),"||")
lever_pulled = (urwid.AttrSpec("#ff3","default"),"//")
furnace_inactive = (urwid.AttrSpec("#b33","default"),"ΩΩ")
furnace_active = (urwid.AttrSpec("#f73","default"),"ϴϴ")
display = "۞ "
coal = " *"
door_closed = (urwid.AttrSpec("#bb3","default"),"⛒ ")
door_opened = (urwid.AttrSpec("#ff3","default"),'⭘ ')
pile = (urwid.AttrSpec("#888","default"),"ӫӫ")
acid = "♒♒"
notImplentedYet = "??"
floor = (urwid.AttrSpec("#336",'default'),"::")
binStorage = "⛛ "
chains = "⛓ "
commLink = "ߐߐ"
grid = "░░"
acids = [(urwid.AttrSpec("#182","default"),"=="),(urwid.AttrSpec("#095","default"),"≈≈"),(urwid.AttrSpec("#282","default"),"≈="),(urwid.AttrSpec("#195","default"),"=≈"),(urwid.AttrSpec("#173","default"),"≈≈")]
foodStuffs = ["՞՞","🍖","☠ ","💀","👂","✋"]
machineries = ["⌺ ","⚙ ","⌼ ","⍯ ","⌸ "]
hub = "🜹 "
ramp = "⍌ "
noClue = "┅┅"
vatSnake = (urwid.AttrSpec("#3fd","default"),"🝇 ")
pipe_lr = "━━"
pipe_lrd = "┳━"
pipe_ld = "┓ "
pipe_lu = "┛ "
pipe_ru = "┗━"
pipe_ud = "┃ "
spray_right_stage1 = "- "
spray_right_stage2 = "= "
spray_right_stage3 = "⚟ "
spray_left_stage1 = " -"
spray_left_stage2 = " ="
spray_left_stage3 = "⚞ "
spray_right_inactive = ": "
spray_left_inactive = " :"
outlet = "◎ "
barricade = "❖❖"
randomStuff1 = ["🜆 ","🜾 ","ꘒ ","ꖻ ","ᵺ "]
randomStuff2 = ["🝍🝍","🝍🝍","🝍🝍","🖵 ","⚲ ","🖵 ","⿴","⿴","⚲ ","🜕 "]
nonWalkableUnkown = "--"
questTargetMarker = (urwid.AttrSpec("white","default"),"xX")
pathMarker = (urwid.AttrSpec("white","default"),"xx")
questPathMarker = pathMarker
invisibleRoom = "⼞"
boiler_inactive = (urwid.AttrSpec("#33b","default"),"伫")
boiler_active = (urwid.AttrSpec("#77f","default"),"伾")
clamp_active = "⮹ "
clamp_inactive = "⮽ "
void = "  "
main_char = (urwid.AttrSpec("white",'default'),"＠")
staffCharacters = ["Ⓐ ","Ⓑ ","Ⓒ ","Ⓓ ",(urwid.AttrSpec("#33f","default"),"Ⓔ "),"Ⓕ ","Ⓖ ","Ⓗ ","Ⓘ ","Ⓙ ","Ⓚ ",(urwid.AttrSpec("#133","default"),"Ⓛ "),"Ⓜ ","Ⓝ ","Ⓞ ","Ⓟ ","Ⓠ ","Ⓡ ","Ⓢ ","Ⓣ ","Ⓤ ","Ⓥ ","Ⓦ ","Ⓧ ","Ⓨ ","Ⓩ "]
staffCharactersByLetter = {"a":"Ⓐ ","b":"Ⓑ ","c":"Ⓒ ","d":"Ⓓ ","e":(urwid.AttrSpec("#33f","default"),"Ⓔ "),"f":"Ⓕ ","g":"Ⓖ ","h":"Ⓗ ","i":"Ⓘ ","j":"Ⓙ ","k":"Ⓚ ","l":(urwid.AttrSpec("#133","default"),"Ⓛ "),"m":"Ⓜ ","n":"Ⓝ ","o":"Ⓞ ","p":"Ⓟ ","q":"Ⓠ ","r":"Ⓡ ","s":"Ⓢ ","t":"Ⓣ ","u":"Ⓤ ","v":"Ⓥ ","w":"Ⓦ ","x":"Ⓧ ","y":"Ⓨ ","z":"Ⓩ "}
winch = "🞇 "
winch_inactive = "🞅 "
winch_active = "🞇 "
scrap_light = "㌱"
scrap_medium = "㌭"
scrap_heavy = "㌕"
