import src.menuFolder.advancedQuestMenu
import src.menuFolder.changeViewsMenu
import src.menuFolder.characterInfoMenu
import src.menuFolder.chatPartnerselection
import src.menuFolder.combatInfoMenu
import src.menuFolder.createQuestMenu
import src.menuFolder.debugMenu
import src.menuFolder.helpMenu
import src.menuFolder.idleChatNPCMenu
import src.menuFolder.implantConnection
import src.menuFolder.inputMenu
import src.menuFolder.instructNPCMenu
import src.menuFolder.instructSubordinatesMenu
import src.menuFolder.inventoryMenu
import src.menuFolder.jobAsMatrixMenu
import src.menuFolder.listActionMenu
import src.menuFolder.mapMenu
import src.menuFolder.nameGhoulMenu
import src.menuFolder.oneKeystrokeMenu
import src.menuFolder.questMenu
import src.menuFolder.roomDutyMenu
import src.menuFolder.roomMenu
import src.menuFolder.roomSourceMenu
import src.menuFolder.selectionMenu
import src.menuFolder.setNPCDutiesMenu
import src.menuFolder.settingMenu
import src.menuFolder.staffAsMatrixMenu
import src.menuFolder.textMenu
import src.menuFolder.viewNPCsMenu
import src.menuFolder.messagesMenu
import src.menuFolder.statusEffectMenu
import src.menuFolder.sliderMenu
import src.menuFolder.teleporterGroupMenu
import src.menuFolder.confirmMenu
import src.menuFolder.directionMenu
import src.menuFolder.TerrainMenu
import src.menuFolder.shoutMenu