import src.statusEffectFolder.addDamageOverTicks
import src.statusEffectFolder.berserk
import src.statusEffectFolder.increaseMaxHealth
import src.statusEffectFolder.increaseHealthRegen
import src.statusEffectFolder.haste
import src.statusEffectFolder.frenzy
import src.statusEffectFolder.slowed
import src.statusEffectFolder.throneSeeker
