import src.statusEffectFolder.AddDamageOverTicks
import src.statusEffectFolder.Berserk
import src.statusEffectFolder.IncreaseMaxHealth
import src.statusEffectFolder.IncreaseHealthRegen
import src.statusEffectFolder.frenzy
