import src.statusEffectFolder.addDamageOverTicks
import src.statusEffectFolder.berserk
import src.statusEffectFolder.IncreaseMaxHealth
import src.statusEffectFolder.IncreaseHealthRegen
import src.statusEffectFolder.haste
import src.statusEffectFolder.frenzy
import src.statusEffectFolder.slowed
