name: Package Game
env:
    GH_TOKEN: ${{ github.token }}

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'master'

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
            path: "./Game/Data"
      - name: install dep and finishing up
        run: |
          sudo apt-get install python3 python3-venv
          cd Game/Data
          python3 -m venv venvFolder
          venvFolder/bin/python3 -m pip install -r requirements.txt
          venvFolder/bin/python3 -m pip install pyinstaller
          venvFolder/bin/pyinstaller executeMe.py
          cd ../../
          tar -czf OfMiceAndMechs-Linux.tar.gz Game
      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: OfMiceAndMechs-Linux
      #     path: |
      #       /Game/*
      #     compression-level: 9
      - name: Create Release
        run: |
            cp ./OfMiceAndMechs-Linux.tar.gz Game/Data/
            cd Game/Data/
            revision = "$(git rev-parse --short HEAD)"
            gh release create $revision ./OfMiceAndMechs-Linux.tar.gz --generate-notes --latest

