name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-win:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: .
        spec: OfMiceAndMechs.spec
    - uses: actions/upload-artifact@v2
      with:
        name: OfMiceAndMechs-win
        path: ./dist/windows
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@python3-10-pyinstaller-5-3
      with:
        path: .
        spec: OfMiceAndMechs.spec
    - uses: actions/upload-artifact@v2
      with:
        name: OfMiceAndMechs-linux
        path: ./dist/linux
