name: Package Game
env:
    GH_TOKEN: ${{ github.token }}

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'master'

jobs:
  build-win:

    runs-on: windows-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
            path: "./Game/Data"
      - name: Download Python Windows Embeddable
        uses: gamedev-thingy/Download-Extract@done
        with:
          # The URL to download from
          url: https://www.python.org/ftp/python/3.12.8/python-3.12.8-embed-amd64.zip
          # Where the files will be extracted to
          destination: "./Game/Data"
          # Name of the downloaded ZIP file
          ZIPname: python-3.12.8-embed-amd64
      - name: install dep and finishing up
        run: |
          Add-Content -Path ./Game/Data/python312._pth -Value "./Lib/site-packages/"
          Add-Content -Path ./Game/Data/python312._pth -Value "import site"
          curl -L https://bootstrap.pypa.io/get-pip.py -o ./Game/Data/get-pip.py
          ./Game/Data/python ./Game/Data/get-pip.py
          ./Game/Data/Scripts/pip install -r ./Game/Data/requirements.txt
          echo "cd Data" | out-file ./Game/lunch_game.bat
          echo "python.exe executeMe.py" | out-file ./Game/lunch_game.bat -Append
          Compress-Archive -Path ./Game/* -Destination OfMiceAndMechs-Win.zip
      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: OfMiceAndMechs-Win
      #     path: |
      #       /Game/*
      #     compression-level: 9
      - name: Create Release
        run: |
            Copy-Item -Path ./OfMiceAndMechs-Win.zip -Destination ./Game/Data
            Set-Location -Path ./Game/Data
            Set-Variable -Name "s" -Value (git rev-parse --short HEAD)
            $s = "Dev-"+$s
            gh release create $s ./OfMiceAndMechs-Win.zip --generate-notes --latest
